branch-defaults:
  master:
    environment: Playgen-env-1
environment-defaults:
  Playgen-env-1:
    branch: null
    repository: null
global:
  application_name: playgen
  default_ec2_keyname: playgen-key
  default_platform: arn:aws:elasticbeanstalk:eu-west-2::platform/Python 3.4 running
    on 64bit Amazon Linux/2.4.2
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
