"""

Revision ID: 08b1dc44bc1c
Revises: 9fc525183bdb
Create Date: 2017-07-22 17:58:37.976019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b1dc44bc1c'
down_revision = '9fc525183bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
