"""

Revision ID: 37cc160d004d
Revises: 08b1dc44bc1c
Create Date: 2017-07-23 00:04:15.340809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37cc160d004d'
down_revision = '08b1dc44bc1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['artist.id'], )
    )
    op.add_column(u'song', sa.Column('artist_title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'song', 'artist_title')
    op.drop_table('followers')
    # ### end Alembic commands ###
