"""Initial Commit

Revision ID: 625c3d83374c
Revises: 50f0078ddb95
Create Date: 2017-07-22 14:46:31.390615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625c3d83374c'
down_revision = '50f0078ddb95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
