"""

Revision ID: 9fc525183bdb
Revises: b5752cb435bb
Create Date: 2017-07-22 14:58:39.331354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc525183bdb'
down_revision = 'b5752cb435bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('my_index', 'artist', ['id'], unique=True, mysql_length=255)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('my_index', 'song', ['title'], unique=True)
    op.drop_index('my_index', table_name='artist')
    # ### end Alembic commands ###
