"""Initial Commit

Revision ID: b5752cb435bb
Revises: 625c3d83374c
Create Date: 2017-07-22 14:47:05.507090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5752cb435bb'
down_revision = '625c3d83374c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'title')
    # ### end Alembic commands ###
